import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { BedrockRuntimeClient, InvokeModelCommand } from '@aws-sdk/client-bedrock-runtime'

const bedrockClient = new BedrockRuntimeClient({
  region: process.env.AWS_REGION!,
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID!,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY!
  }
})

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()

    // Auth check
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { text_id, content } = await request.json()

    // Validate inputs
    if (!text_id || !content) {
      return NextResponse.json(
        { error: 'Missing required fields: text_id, content' },
        { status: 400 }
      )
    }

    // Call Bedrock to generate scene description
    const prompt = `Summarize the main literary content in this passage in 2-3 sentences. Focus on:
- Setting (where/when the scene takes place)
- Characters (who is present)
- Main action (what happens)

IMPORTANT:
- Skip any Project Gutenberg license/copyright header text at the beginning
- Find the actual story content (usually starts after headers/metadata)
- Summarize ONLY the narrative/literary portion

Do NOT describe writing style, tone, or literary techniques. Keep it factual and neutral.

TEXT:
${content}

Output ONLY the summary of the story content. No meta-commentary, apologies, or explanations. Just the 2-3 sentence summary.`

    const input = {
      modelId: 'us.anthropic.claude-3-5-haiku-20241022-v1:0',  // Fixed: Using available model
      contentType: 'application/json',
      accept: 'application/json',
      body: JSON.stringify({
        anthropic_version: 'bedrock-2023-05-31',
        max_tokens: 500,
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.5
      })
    }

    const command = new InvokeModelCommand(input)
    const response = await bedrockClient.send(command)

    // Decode Bedrock response
    const responseBody = JSON.parse(new TextDecoder().decode(response.body))
    const description = responseBody.content?.[0]?.text?.trim()

    if (!description) {
      throw new Error('No description generated by Bedrock')
    }

    // Cache in database (update metadata.plot_summary)
    const { data: existingText } = await supabase
      .from('source_texts')
      .select('metadata')
      .eq('id', text_id)
      .single()

    const updatedMetadata = {
      ...existingText?.metadata,
      plot_summary: description,
      generated_at: new Date().toISOString()
    }

    const { error: updateError } = await supabase
      .from('source_texts')
      .update({ metadata: updatedMetadata })
      .eq('id', text_id)

    if (updateError) {
      console.error('Failed to cache description in DB:', updateError)
      // Non-critical error - still return description
    }

    return NextResponse.json({ description })
  } catch (error: any) {
    console.error('Scene description generation error:', error)
    return NextResponse.json(
      { error: error.message || 'Failed to generate description' },
      { status: 500 }
    )
  }
}
